import { NHM, type Dino } from './dinos.ts';

const WIKI = (page: string) => ({ label: 'Wikipedia', url: `https://en.wikipedia.org/wiki/${page}` });

/** The 22 animals that are won in challenges. Same rounding rules as the starters. */
export const WON: Dino[] = [
  {
    id: 'spinosaurus',
    name: 'Spinosaurus',
    pronounce: { sv: 'spi-no-SAU-rus', en: 'SPINE-oh-SORE-us' },
    meaning: { sv: 'Taggödla', en: 'Spine lizard' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 99,
    toMya: 94,
    lengthM: 14,
    heightM: 5,
    weightKg: 7000,
    sizeLike: { sv: 'Längre än en buss', en: 'Longer than a bus' },
    diet: 'piscivore',
    found: { sv: 'Egypten och Marocko', en: 'Egypt and Morocco' },
    short: {
      sv: 'En jättelik rovdinosaurie med ett stort segel på ryggen. Den fångade fisk i floder.',
      en: 'A giant meat-eater with a big sail on its back. It caught fish in rivers.',
    },
    long: {
      sv: 'Spinosaurus är en av de längsta rovdinosaurier man känner till. Nosen var lång och smal som på en krokodil, med raka tänder som passade för att hålla fast hal fisk. Seglet på ryggen hölls uppe av långa taggar från ryggraden. Forskare är inte överens om hur mycket den simmade och hur mycket den vadade.',
      en: 'Spinosaurus is one of the longest meat-eating dinosaurs known. Its snout was long and narrow like a crocodile\'s, with straight teeth good for gripping slippery fish. The sail on its back was held up by long spines from its backbone. Scientists do not agree on how much it swam and how much it waded.',
    },
    facts: [
      { sv: 'Taggarna i seglet kunde bli längre än en vuxen människa.', en: 'The spines in its sail could be taller than a grown-up.' },
      { sv: 'De första fossilen förstördes i ett krig, så forskarna fick börja om.', en: 'The first fossils were destroyed in a war, so scientists had to start again.' },
      { sv: 'Svansen var platt som en paddel.', en: 'Its tail was flat like a paddle.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på djupa, mullrande ljud som hos krokodiler.',
      en: 'Nobody knows for sure. Scientists guess at deep, rumbling sounds like crocodiles make.',
    },
    starter: false,
    colour: 'guess',
    source: NHM('spinosaurus'),
  },
  {
    id: 'allosaurus',
    name: 'Allosaurus',
    pronounce: { sv: 'al-lo-SAU-rus', en: 'AL-oh-SORE-us' },
    meaning: { sv: 'Annorlunda ödla', en: 'Different lizard' },
    group: 'dinosaur',
    period: 'jurassic',
    fromMya: 155,
    toMya: 145,
    lengthM: 9,
    heightM: 3,
    weightKg: 2000,
    sizeLike: { sv: 'Lång som en buss', en: 'As long as a bus' },
    diet: 'carnivore',
    found: { sv: 'USA och Portugal', en: 'USA and Portugal' },
    short: {
      sv: 'Juratidens stora rovdjur. Den jagade bland annat Stegosaurus.',
      en: 'The big hunter of the Jurassic. It hunted Stegosaurus, among others.',
    },
    long: {
      sv: 'Allosaurus levde långt före Tyrannosaurus rex och var den vanligaste stora köttätaren på sin tid. Den hade tre fingrar med kraftiga klor på varje hand och små horn ovanför ögonen. Man har hittat ett Allosaurus-ben med ett hål som passar en svanstagg från Stegosaurus.',
      en: 'Allosaurus lived long before Tyrannosaurus rex and was the most common large meat-eater of its time. It had three fingers with strong claws on each hand and small horns above its eyes. An Allosaurus bone has been found with a hole that fits a Stegosaurus tail spike.',
    },
    facts: [
      { sv: 'Den hade tre fingrar på varje hand.', en: 'It had three fingers on each hand.' },
      { sv: 'Den hade små horn ovanför ögonen.', en: 'It had small horns above its eyes.' },
      { sv: 'Den levde nästan 90 miljoner år före Tyrannosaurus rex.', en: 'It lived almost 90 million years before Tyrannosaurus rex.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på djupa ljud med stängd mun.',
      en: 'Nobody knows for sure. Scientists guess at deep sounds made with its mouth closed.',
    },
    starter: false,
    colour: 'guess',
    source: NHM('allosaurus'),
  },
  {
    id: 'giganotosaurus',
    name: 'Giganotosaurus',
    pronounce: { sv: 'gi-ga-no-to-SAU-rus', en: 'JIG-an-OH-toe-SORE-us' },
    meaning: { sv: 'Jättelik sydödla', en: 'Giant southern lizard' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 99,
    toMya: 95,
    lengthM: 12.5,
    heightM: 4.5,
    weightKg: 8000,
    sizeLike: { sv: 'Ungefär lika stor som Tyrannosaurus rex', en: 'About as big as Tyrannosaurus rex' },
    diet: 'carnivore',
    found: { sv: 'Argentina', en: 'Argentina' },
    short: {
      sv: 'En av de största köttätarna någonsin. Den levde i Sydamerika.',
      en: 'One of the biggest meat-eaters ever. It lived in South America.',
    },
    long: {
      sv: 'Giganotosaurus var ungefär lika lång som Tyrannosaurus rex men levde 30 miljoner år tidigare och på en annan kontinent. Skallen var lång och tänderna tunna och vassa som knivar, bra för att skära i kött. Den levde samtidigt som några av de största långhalsarna.',
      en: 'Giganotosaurus was about as long as Tyrannosaurus rex but lived 30 million years earlier and on another continent. Its skull was long and its teeth were thin and sharp like knives, good for slicing meat. It lived alongside some of the largest long-necked dinosaurs.',
    },
    facts: [
      { sv: 'Den hittades av en man som letade fossil på fritiden.', en: 'It was found by a man who hunted fossils as a hobby.' },
      { sv: 'Skallen var längre än en vuxen människa.', en: 'Its skull was longer than a grown-up is tall.' },
      { sv: 'Den hade tre fingrar på varje hand.', en: 'It had three fingers on each hand.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på djupa, mullrande ljud.',
      en: 'Nobody knows for sure. Scientists guess at deep, rumbling sounds.',
    },
    starter: false,
    colour: 'guess',
    source: NHM('giganotosaurus'),
  },
  {
    id: 'carnotaurus',
    name: 'Carnotaurus',
    pronounce: { sv: 'kar-no-TAU-rus', en: 'KAR-no-TORE-us' },
    meaning: { sv: 'Köttätande tjur', en: 'Meat-eating bull' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 72,
    toMya: 69,
    lengthM: 8,
    heightM: 3,
    weightKg: 1500,
    sizeLike: { sv: 'Lång som en liten lastbil', en: 'As long as a small lorry' },
    diet: 'carnivore',
    found: { sv: 'Argentina', en: 'Argentina' },
    short: {
      sv: 'En köttätare med två horn som en tjur och pyttesmå armar.',
      en: 'A meat-eater with two horns like a bull and tiny arms.',
    },
    long: {
      sv: 'Carnotaurus hade ett kort, högt huvud med ett tjockt horn över varje öga. Armarna var ännu mindre än hos Tyrannosaurus rex och kunde knappt röras. Benen var långa, så den var troligen en snabb löpare. Man har hittat avtryck av huden, som var täckt av små fjäll och knölar.',
      en: 'Carnotaurus had a short, tall head with a thick horn over each eye. Its arms were even smaller than those of Tyrannosaurus rex and could hardly move. Its legs were long, so it was probably a fast runner. Prints of its skin have been found, covered in small scales and bumps.',
    },
    facts: [
      { sv: 'Armarna var mindre än hos Tyrannosaurus rex.', en: 'Its arms were smaller than those of Tyrannosaurus rex.' },
      { sv: 'Man vet hur huden såg ut tack vare avtryck i stenen.', en: 'We know what its skin looked like thanks to prints in the rock.' },
      { sv: 'Bara ett enda skelett har hittats.', en: 'Only one skeleton has ever been found.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på djupa, dova ljud.',
      en: 'Nobody knows for sure. Scientists guess at deep, muffled sounds.',
    },
    starter: false,
    colour: 'guess',
    source: NHM('carnotaurus'),
  },
  {
    id: 'dilophosaurus',
    name: 'Dilophosaurus',
    pronounce: { sv: 'di-lo-fo-SAU-rus', en: 'die-LOAF-oh-SORE-us' },
    meaning: { sv: 'Ödla med två kammar', en: 'Two-crested lizard' },
    group: 'dinosaur',
    period: 'jurassic',
    fromMya: 193,
    toMya: 183,
    lengthM: 6,
    heightM: 2,
    weightKg: 400,
    sizeLike: { sv: 'Lång som en bil, tung som en häst', en: 'As long as a car, as heavy as a horse' },
    diet: 'carnivore',
    found: { sv: 'USA', en: 'USA' },
    short: {
      sv: 'En tidig köttätare med två tunna kammar på huvudet.',
      en: 'An early meat-eater with two thin crests on its head.',
    },
    long: {
      sv: 'Dilophosaurus levde tidigt under jura och var ett av de största rovdjuren på sin tid. Kammarna på huvudet var tunna och användes troligen för att visa upp sig. I filmer sprutar den gift och har en krage runt halsen, men det är påhitt: inga fossil visar något sådant.',
      en: 'Dilophosaurus lived early in the Jurassic and was one of the biggest hunters of its time. The crests on its head were thin and were probably used for showing off. In films it spits venom and has a frill around its neck, but that is made up: no fossils show anything like it.',
    },
    facts: [
      { sv: 'Den sprutade inte gift. Det är påhittat för film.', en: 'It did not spit venom. That was made up for a film.' },
      { sv: 'Den hade ingen krage runt halsen.', en: 'It had no frill around its neck.' },
      { sv: 'Den levde över 100 miljoner år före Tyrannosaurus rex.', en: 'It lived over 100 million years before Tyrannosaurus rex.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på väsningar och djupa ljud.',
      en: 'Nobody knows for sure. Scientists guess at hisses and deep sounds.',
    },
    starter: false,
    colour: 'guess',
    source: NHM('dilophosaurus'),
  },
  {
    id: 'deinonychus',
    name: 'Deinonychus',
    pronounce: { sv: 'dej-NO-ny-kus', en: 'die-NON-ih-kus' },
    meaning: { sv: 'Fruktansvärd klo', en: 'Terrible claw' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 115,
    toMya: 108,
    lengthM: 3.4,
    heightM: 1.2,
    weightKg: 75,
    sizeLike: { sv: 'Tung som en vuxen människa', en: 'As heavy as a grown-up' },
    diet: 'carnivore',
    found: { sv: 'USA', en: 'USA' },
    short: {
      sv: 'En snabb, fjäderklädd jägare med en stor klo på varje fot.',
      en: 'A fast, feathered hunter with a big claw on each foot.',
    },
    long: {
      sv: 'Deinonychus var större släkting till Velociraptor. Det är egentligen den som filmernas "raptorer" liknar i storlek. När den upptäcktes på 1960-talet ändrade den hur forskare såg på dinosaurier: inte tröga ödlor, utan snabba och aktiva djur som var släkt med fåglar.',
      en: 'Deinonychus was a bigger relative of Velociraptor. It is really the one that film "raptors" match in size. When it was discovered in the 1960s it changed how scientists saw dinosaurs: not slow lizards, but fast and active animals related to birds.',
    },
    facts: [
      { sv: 'Klon på foten var lika lång som en hand.', en: 'The claw on its foot was as long as a hand.' },
      { sv: 'Filmernas raptorer är lika stora som Deinonychus.', en: 'Film raptors are the size of Deinonychus.' },
      { sv: 'Svansen var stel och hjälpte den hålla balansen.', en: 'Its tail was stiff and helped it keep its balance.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på väsningar och fågelliknande ljud.',
      en: 'Nobody knows for sure. Scientists guess at hisses and bird-like sounds.',
    },
    starter: false,
    colour: 'relatives',
    source: NHM('deinonychus'),
  },
  {
    id: 'compsognathus',
    name: 'Compsognathus',
    pronounce: { sv: 'komp-sog-NA-tus', en: 'komp-sog-NATH-us' },
    meaning: { sv: 'Elegant käke', en: 'Elegant jaw' },
    group: 'dinosaur',
    period: 'jurassic',
    fromMya: 151,
    toMya: 145,
    lengthM: 1,
    heightM: 0.4,
    weightKg: 3,
    sizeLike: { sv: 'Stor som en höna', en: 'The size of a chicken' },
    diet: 'carnivore',
    found: { sv: 'Tyskland och Frankrike', en: 'Germany and France' },
    short: {
      sv: 'En av de minsta dinosaurierna. Den jagade ödlor och insekter.',
      en: 'One of the smallest dinosaurs. It hunted lizards and insects.',
    },
    long: {
      sv: 'Compsognathus var länge den minsta dinosaurie man kände till. Den sprang på två långa bakben och fångade små djur. I magen på ett av fossilen ligger en hel liten ödla, så forskarna vet precis vad den åt.',
      en: 'For a long time Compsognathus was the smallest dinosaur known. It ran on two long back legs and caught small animals. Inside the stomach of one fossil lies a whole small lizard, so scientists know exactly what it ate.',
    },
    facts: [
      { sv: 'Den vägde ungefär som en katt.', en: 'It weighed about as much as a cat.' },
      { sv: 'Ett fossil har en ödla kvar i magen.', en: 'One fossil still has a lizard in its stomach.' },
      { sv: 'Bara två skelett har hittats.', en: 'Only two skeletons have been found.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på pip och kvitter som hos små fåglar.',
      en: 'Nobody knows for sure. Scientists guess at chirps and squeaks like small birds.',
    },
    starter: false,
    colour: 'relatives',
    source: NHM('compsognathus'),
  },
  {
    id: 'gallimimus',
    name: 'Gallimimus',
    pronounce: { sv: 'gal-li-MI-mus', en: 'GAL-ih-MY-mus' },
    meaning: { sv: 'Liknar en höna', en: 'Chicken mimic' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 72,
    toMya: 68,
    lengthM: 6,
    heightM: 3,
    weightKg: 440,
    sizeLike: { sv: 'Som en jättestor struts', en: 'Like a very big ostrich' },
    diet: 'omnivore',
    found: { sv: 'Mongoliet', en: 'Mongolia' },
    short: {
      sv: 'En snabb löpare som såg ut som en struts med lång svans.',
      en: 'A fast runner that looked like an ostrich with a long tail.',
    },
    long: {
      sv: 'Gallimimus hade långa ben, lång hals och en tandlös näbb. Den var en av de snabbaste dinosaurierna och sprang troligen ifrån sina fiender. Forskare tror att den åt både växter och smådjur.',
      en: 'Gallimimus had long legs, a long neck and a toothless beak. It was one of the fastest dinosaurs and probably outran its enemies. Scientists think it ate both plants and small animals.',
    },
    facts: [
      { sv: 'Den hade inga tänder.', en: 'It had no teeth.' },
      { sv: 'Den kan ha sprungit lika fort som en galopperande häst.', en: 'It may have run as fast as a galloping horse.' },
      { sv: 'Ögonen satt på sidorna av huvudet, så den såg åt nästan alla håll.', en: 'Its eyes sat on the sides of its head, so it could see almost all around.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på dova, trummande ljud som hos strutsar.',
      en: 'Nobody knows for sure. Scientists guess at low, booming sounds like ostriches make.',
    },
    starter: false,
    colour: 'guess',
    source: NHM('gallimimus'),
  },
  {
    id: 'oviraptor',
    name: 'Oviraptor',
    pronounce: { sv: 'o-vi-RAP-tor', en: 'OH-vih-RAP-tor' },
    meaning: { sv: 'Äggtjuv', en: 'Egg thief' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 76,
    toMya: 72,
    lengthM: 1.8,
    heightM: 1,
    weightKg: 30,
    sizeLike: { sv: 'Stor som en stor hund', en: 'The size of a big dog' },
    diet: 'omnivore',
    found: { sv: 'Mongoliet', en: 'Mongolia' },
    short: {
      sv: 'En fjäderklädd dinosaurie med näbb. Namnet betyder äggtjuv, men det var ett misstag.',
      en: 'A feathered dinosaur with a beak. Its name means egg thief, but that was a mistake.',
    },
    long: {
      sv: 'Oviraptor hittades ovanpå ett bo med ägg, och forskarna trodde att den stal dem. Senare hittade man nära släktingar som satt på likadana bon med vingarna utbredda över äggen, precis som ruvande fåglar. Äggen var alltså dess egna. Namnet fick ändå stå kvar.',
      en: 'Oviraptor was found on top of a nest of eggs, and scientists thought it was stealing them. Later, close relatives were found sitting on the same kind of nests with their arms spread over the eggs, just like brooding birds. So the eggs were its own. The name stayed anyway.',
    },
    facts: [
      { sv: 'Den var ingen äggtjuv. Den vaktade sina egna ägg.', en: 'It was no egg thief. It was guarding its own eggs.' },
      { sv: 'Den hade näbb men inga tänder.', en: 'It had a beak but no teeth.' },
      { sv: 'Släktingar har hittats ruvande på sina bon.', en: 'Relatives have been found brooding on their nests.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på fågelliknande ljud.',
      en: 'Nobody knows for sure. Scientists guess at bird-like sounds.',
    },
    starter: false,
    colour: 'relatives',
    source: NHM('oviraptor'),
  },
  {
    id: 'therizinosaurus',
    name: 'Therizinosaurus',
    pronounce: { sv: 'te-ri-si-no-SAU-rus', en: 'THERRY-zin-oh-SORE-us' },
    meaning: { sv: 'Lieödla', en: 'Scythe lizard' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 72,
    toMya: 68,
    lengthM: 10,
    heightM: 5,
    weightKg: 5000,
    sizeLike: { sv: 'Tung som en elefant', en: 'As heavy as an elephant' },
    diet: 'herbivore',
    found: { sv: 'Mongoliet', en: 'Mongolia' },
    short: {
      sv: 'En växtätare med de längsta klorna hos något djur som funnits.',
      en: 'A plant-eater with the longest claws of any animal that ever lived.',
    },
    long: {
      sv: 'Therizinosaurus tillhörde samma stora grupp som köttätarna men åt växter. Klorna kunde bli runt en halv meter långa och användes troligen för att dra ner grenar och för att skrämma rovdjur. Bara delar av skelettet har hittats, så forskarna har byggt bilden med hjälp av släktingar.',
      en: 'Therizinosaurus belonged to the same large group as the meat-eaters but ate plants. Its claws could be around half a metre long and were probably used to pull down branches and to scare off hunters. Only parts of the skeleton have been found, so scientists have built the picture with help from its relatives.',
    },
    facts: [
      { sv: 'Klorna var ungefär en halv meter långa.', en: 'Its claws were about half a metre long.' },
      { sv: 'Den åt växter trots de enorma klorna.', en: 'It ate plants in spite of its huge claws.' },
      { sv: 'Först trodde forskarna att klorna kom från en jättesköldpadda.', en: 'At first scientists thought the claws came from a giant turtle.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på djupa, dova ljud.',
      en: 'Nobody knows for sure. Scientists guess at deep, muffled sounds.',
    },
    starter: false,
    colour: 'relatives',
    source: NHM('therizinosaurus'),
  },
  {
    id: 'archaeopteryx',
    name: 'Archaeopteryx',
    pronounce: { sv: 'ar-ke-OP-te-ryx', en: 'ark-ee-OP-ter-ix' },
    meaning: { sv: 'Urgammal vinge', en: 'Ancient wing' },
    group: 'dinosaur',
    period: 'jurassic',
    fromMya: 151,
    toMya: 148,
    lengthM: 0.5,
    heightM: 0.3,
    weightKg: 1,
    sizeLike: { sv: 'Stor som en kråka', en: 'The size of a crow' },
    diet: 'carnivore',
    found: { sv: 'Tyskland', en: 'Germany' },
    short: {
      sv: 'En liten dinosaurie med vingar och fjädrar. Den visar hur fåglarna kom till.',
      en: 'A small dinosaur with wings and feathers. It shows how birds came to be.',
    },
    long: {
      sv: 'Archaeopteryx hade fjädrar och vingar som en fågel, men också tänder, klor på vingarna och en lång svans med ben i, som en dinosaurie. Den hittades på 1860-talet och blev ett av de viktigaste fossilen någonsin, eftersom den visar att fåglar härstammar från dinosaurier.',
      en: 'Archaeopteryx had feathers and wings like a bird, but also teeth, claws on its wings and a long bony tail, like a dinosaur. It was found in the 1860s and became one of the most important fossils ever, because it shows that birds come from dinosaurs.',
    },
    facts: [
      { sv: 'Den hade tänder i näbben.', en: 'It had teeth in its jaws.' },
      { sv: 'Den hade klor på vingarna.', en: 'It had claws on its wings.' },
      { sv: 'Fossilen är så fina att varje fjäder syns.', en: 'The fossils are so fine that every feather shows.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på enkla skrin, inte sång som hos dagens småfåglar.',
      en: 'Nobody knows for sure. Scientists guess at simple squawks, not song like small birds today.',
    },
    starter: false,
    colour: 'known',
    colourDisputed: true,
    source: NHM('archaeopteryx'),
  },
  {
    id: 'microraptor',
    name: 'Microraptor',
    pronounce: { sv: 'MI-kro-rap-tor', en: 'MIKE-row-rap-tor' },
    meaning: { sv: 'Liten rövare', en: 'Small thief' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 125,
    toMya: 120,
    lengthM: 0.8,
    heightM: 0.5,
    weightKg: 1,
    sizeLike: { sv: 'Stor som en kråka', en: 'The size of a crow' },
    diet: 'carnivore',
    found: { sv: 'Kina', en: 'China' },
    short: {
      sv: 'En pytteliten dinosaurie med fyra vingar. Fjädrarna var svarta och glänsande.',
      en: 'A tiny dinosaur with four wings. Its feathers were black and shiny.',
    },
    long: {
      sv: 'Microraptor hade långa fjädrar både på armarna och på benen, alltså fyra vingar. Den kunde glidflyga mellan träden och kanske flaxa lite. Det här är en av få dinosaurier där forskarna faktiskt vet färgen: i fjädrarna finns rester av färgkorn som visar att de var svarta med blå glans, som på en korp.',
      en: 'Microraptor had long feathers on both its arms and its legs, so it had four wings. It could glide between trees and perhaps flap a little. This is one of the few dinosaurs whose colour scientists actually know: its feathers hold traces of colour grains showing they were black with a blue sheen, like a raven.',
    },
    facts: [
      { sv: 'Den hade fyra vingar.', en: 'It had four wings.' },
      { sv: 'Forskare vet att den var svart och glänsande.', en: 'Scientists know it was black and shiny.' },
      { sv: 'Fossil har hittats med fisk, fågel och ödla i magen.', en: 'Fossils have been found with fish, bird and lizard in the stomach.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på skrin som hos fåglar.',
      en: 'Nobody knows for sure. Scientists guess at bird-like squawks.',
    },
    starter: false,
    colour: 'known',
    source: NHM('microraptor'),
  },
  {
    id: 'argentinosaurus',
    name: 'Argentinosaurus',
    pronounce: { sv: 'ar-gen-ti-no-SAU-rus', en: 'AR-jen-TEEN-oh-SORE-us' },
    meaning: { sv: 'Ödlan från Argentina', en: 'Argentina lizard' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 96,
    toMya: 92,
    lengthM: 35,
    heightM: 12,
    weightKg: 70000,
    sizeLike: { sv: 'Lång som tre bussar', en: 'As long as three buses' },
    diet: 'herbivore',
    found: { sv: 'Argentina', en: 'Argentina' },
    short: {
      sv: 'Ett av de största djur som någonsin gått på land.',
      en: 'One of the biggest animals ever to walk on land.',
    },
    long: {
      sv: 'Av Argentinosaurus har man bara hittat några få ben, men de är enorma: en enda ryggkota är högre än ett barn. Därför är längden och vikten uppskattningar, och olika forskare får olika svar. Ungarna kläcktes ur ägg stora som fotbollar och växte mycket fort.',
      en: 'Only a few bones of Argentinosaurus have been found, but they are enormous: a single back bone is taller than a child. That is why its length and weight are estimates, and different scientists get different answers. The babies hatched from eggs the size of footballs and grew very fast.',
    },
    facts: [
      { sv: 'Den vägde ungefär som tio elefanter.', en: 'It weighed about as much as ten elephants.' },
      { sv: 'En enda ryggkota är högre än ett barn.', en: 'A single back bone is taller than a child.' },
      { sv: 'Den hittades av en bonde som trodde att benet var en stock.', en: 'It was found by a farmer who thought the bone was a log.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Så stora djur gör ofta mycket djupa ljud.',
      en: 'Nobody knows for sure. Animals this big often make very deep sounds.',
    },
    starter: false,
    colour: 'guess',
    source: NHM('argentinosaurus'),
  },
  {
    id: 'apatosaurus',
    name: 'Apatosaurus',
    pronounce: { sv: 'a-pa-to-SAU-rus', en: 'ah-PAT-oh-SORE-us' },
    meaning: { sv: 'Vilseledande ödla', en: 'Deceptive lizard' },
    group: 'dinosaur',
    period: 'jurassic',
    fromMya: 152,
    toMya: 151,
    lengthM: 22,
    heightM: 6,
    weightKg: 22000,
    sizeLike: { sv: 'Lång som två bussar', en: 'As long as two buses' },
    diet: 'herbivore',
    found: { sv: 'USA', en: 'USA' },
    short: {
      sv: 'En kraftig långhals med tjock hals och lång svans.',
      en: 'A sturdy long-necked dinosaur with a thick neck and a long tail.',
    },
    long: {
      sv: 'Apatosaurus var kortare men mycket tyngre än sin släkting Diplodocus. Halsen var ovanligt bred och kraftig. Den är nära släkt med Brontosaurus, och länge trodde forskarna att de två var samma djur. Numera räknas de oftast som två olika.',
      en: 'Apatosaurus was shorter but much heavier than its relative Diplodocus. Its neck was unusually wide and strong. It is closely related to Brontosaurus, and for a long time scientists thought the two were the same animal. Today they are usually counted as two different ones.',
    },
    facts: [
      { sv: 'Den är nära släkt med Brontosaurus.', en: 'It is a close relative of Brontosaurus.' },
      { sv: 'Den var tyngre än Diplodocus trots att den var kortare.', en: 'It was heavier than Diplodocus even though it was shorter.' },
      { sv: 'I många år satt fel huvud på skelettet på museer.', en: 'For many years museums showed its skeleton with the wrong head.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Kanske djupa ljud, och kanske en smäll från svansen.',
      en: 'Nobody knows for sure. Maybe deep sounds, and maybe a crack from its tail.',
    },
    starter: false,
    colour: 'relatives',
    source: NHM('apatosaurus'),
  },
  {
    id: 'iguanodon',
    name: 'Iguanodon',
    pronounce: { sv: 'i-GUA-no-don', en: 'ig-WAH-no-don' },
    meaning: { sv: 'Leguantand', en: 'Iguana tooth' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 126,
    toMya: 122,
    lengthM: 10,
    heightM: 3.5,
    weightKg: 4500,
    sizeLike: { sv: 'Lång som en buss', en: 'As long as a bus' },
    diet: 'herbivore',
    found: { sv: 'Belgien, England och Tyskland', en: 'Belgium, England and Germany' },
    short: {
      sv: 'En stor växtätare med en vass tagg på varje tumme.',
      en: 'A big plant-eater with a sharp spike on each thumb.',
    },
    long: {
      sv: 'Iguanodon var en av de allra första dinosaurier som fick ett namn, redan 1825. Då hade man bara tänder och några ben, och tumtaggen ritades som ett horn på nosen. Först när hela skelett hittades i en belgisk kolgruva förstod man hur den såg ut. Den kunde gå både på två och fyra ben.',
      en: 'Iguanodon was one of the very first dinosaurs to be named, back in 1825. At that time only teeth and a few bones were known, and the thumb spike was drawn as a horn on its nose. Only when whole skeletons were found in a Belgian coal mine did people understand what it looked like. It could walk on both two and four legs.',
    },
    facts: [
      { sv: 'Tumtaggen ritades först som ett horn på nosen.', en: 'The thumb spike was first drawn as a horn on its nose.' },
      { sv: 'Den fick sitt namn innan ordet dinosaurie fanns.', en: 'It was named before the word dinosaur existed.' },
      { sv: 'Över 30 skelett hittades i samma kolgruva.', en: 'Over 30 skeletons were found in the same coal mine.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på låga brummanden.',
      en: 'Nobody knows for sure. Scientists guess at low grunts.',
    },
    starter: false,
    colour: 'guess',
    source: NHM('iguanodon'),
  },
  {
    id: 'parasaurolophus',
    name: 'Parasaurolophus',
    pronounce: { sv: 'pa-ra-sau-RO-lo-fus', en: 'PA-ra-saw-ROL-off-us' },
    meaning: { sv: 'Nära kamödlan', en: 'Near crested lizard' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 76,
    toMya: 73,
    lengthM: 9.5,
    heightM: 4,
    weightKg: 3000,
    sizeLike: { sv: 'Lång som en buss', en: 'As long as a bus' },
    diet: 'herbivore',
    found: { sv: 'USA och Kanada', en: 'USA and Canada' },
    short: {
      sv: 'En växtätare med en lång, ihålig kam på huvudet som den kunde tuta med.',
      en: 'A plant-eater with a long, hollow crest on its head that it could honk with.',
    },
    long: {
      sv: 'Kammen på Parasaurolophus var ett rör som gick från nosen, upp över huvudet och tillbaka igen. När djuret blåste luft genom röret blev det ett djupt ljud, som i en trombon. Forskare har byggt modeller av kammen och spelat upp hur den kan ha låtit. Det gör den till en av få dinosaurier vars läte vi vet något om.',
      en: 'The crest of Parasaurolophus was a tube running from its nose, up over its head and back again. When the animal blew air through the tube it made a deep sound, like a trombone. Scientists have built models of the crest and played back what it may have sounded like. That makes it one of the few dinosaurs whose call we know something about.',
    },
    facts: [
      { sv: 'Kammen kunde bli längre än en vuxen människa.', en: 'Its crest could be longer than a grown-up is tall.' },
      { sv: 'Kammen var ihålig som ett blåsinstrument.', en: 'The crest was hollow like a wind instrument.' },
      { sv: 'Den hade hundratals tänder som malde växter.', en: 'It had hundreds of teeth that ground up plants.' },
    ],
    sound: {
      sv: 'Här vet forskare mer än vanligt: den ihåliga kammen gav ett djupt, tutande ljud, ungefär som en trombon eller en mistlur.',
      en: 'Here scientists know more than usual: the hollow crest gave a deep, honking sound, a bit like a trombone or a foghorn.',
    },
    starter: false,
    colour: 'guess',
    source: NHM('parasaurolophus'),
  },
  {
    id: 'maiasaura',
    name: 'Maiasaura',
    pronounce: { sv: 'ma-ja-SAU-ra', en: 'MY-ah-SORE-ah' },
    meaning: { sv: 'God mamma-ödla', en: 'Good mother lizard' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 80,
    toMya: 75,
    lengthM: 9,
    heightM: 3,
    weightKg: 3000,
    sizeLike: { sv: 'Lång som en buss', en: 'As long as a bus' },
    diet: 'herbivore',
    found: { sv: 'USA', en: 'USA' },
    short: {
      sv: 'En växtätare som byggde bon och tog hand om sina ungar.',
      en: 'A plant-eater that built nests and looked after its babies.',
    },
    long: {
      sv: 'Maiasaura hittades tillsammans med bon, ägg och ungar i olika åldrar. Ungarnas ben var för svaga för att gå när de kläcktes, men tänderna var slitna. Det betyder att föräldrarna kom med mat till boet. Bona låg tätt ihop, som i en fågelkoloni, och djuren levde i stora flockar.',
      en: 'Maiasaura was found together with nests, eggs and young of different ages. The babies\' legs were too weak to walk when they hatched, but their teeth were worn. That means the parents brought food to the nest. The nests lay close together, like in a bird colony, and the animals lived in large herds.',
    },
    facts: [
      { sv: 'Föräldrarna kom med mat till ungarna i boet.', en: 'The parents brought food to the babies in the nest.' },
      { sv: 'En flock kunde ha tusentals djur.', en: 'A herd could have thousands of animals.' },
      { sv: 'Ett Maiasaura-ben har varit med i rymden.', en: 'A Maiasaura bone has been to space.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Djur som lever i flock brukar ropa till varandra, så forskare gissar på tutande och brummande ljud.',
      en: 'Nobody knows for sure. Animals that live in herds usually call to each other, so scientists guess at honks and grunts.',
    },
    starter: false,
    colour: 'guess',
    source: NHM('maiasaura'),
  },
  {
    id: 'pachycephalosaurus',
    name: 'Pachycephalosaurus',
    pronounce: { sv: 'pa-ky-se-fa-lo-SAU-rus', en: 'PACK-ee-SEF-ah-loh-SORE-us' },
    meaning: { sv: 'Tjockskallig ödla', en: 'Thick-headed lizard' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 70,
    toMya: 66,
    lengthM: 4.5,
    heightM: 1.8,
    weightKg: 450,
    sizeLike: { sv: 'Lång som en bil', en: 'As long as a car' },
    diet: 'herbivore',
    found: { sv: 'USA och Kanada', en: 'USA and Canada' },
    short: {
      sv: 'En dinosaurie med en tjock kupol av ben på huvudet.',
      en: 'A dinosaur with a thick dome of bone on its head.',
    },
    long: {
      sv: 'Skalltaket på Pachycephalosaurus kunde vara över 20 centimeter tjockt och omgavs av små knölar och taggar. Länge trodde man att de stångades med huvudena som baggar. Forskare är inte överens: en del tror att de i stället knuffade varandra i sidan. Skador som läkt på flera kupoler tyder på att huvudet verkligen användes i strid.',
      en: 'The skull roof of Pachycephalosaurus could be over 20 centimetres thick and was ringed by small bumps and spikes. For a long time people thought they butted heads like rams. Scientists do not agree: some think they shoved each other in the side instead. Healed injuries on several domes suggest the head really was used in fights.',
    },
    facts: [
      { sv: 'Skallbenet var över 20 centimeter tjockt.', en: 'Its skull bone was over 20 centimetres thick.' },
      { sv: 'Den gick på två ben.', en: 'It walked on two legs.' },
      { sv: 'Den levde samtidigt som Tyrannosaurus rex.', en: 'It lived at the same time as Tyrannosaurus rex.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på grymtningar och fnysningar.',
      en: 'Nobody knows for sure. Scientists guess at grunts and snorts.',
    },
    starter: false,
    colour: 'guess',
    source: NHM('pachycephalosaurus'),
  },
  {
    id: 'protoceratops',
    name: 'Protoceratops',
    pronounce: { sv: 'pro-to-SE-ra-tops', en: 'pro-toe-SERRA-tops' },
    meaning: { sv: 'Första hornansiktet', en: 'First horned face' },
    group: 'dinosaur',
    period: 'cretaceous',
    fromMya: 75,
    toMya: 71,
    lengthM: 1.8,
    heightM: 0.8,
    weightKg: 180,
    sizeLike: { sv: 'Stor som ett får', en: 'The size of a sheep' },
    diet: 'herbivore',
    found: { sv: 'Mongoliet och Kina', en: 'Mongolia and China' },
    short: {
      sv: 'En liten släkting till Triceratops, med krage men utan horn.',
      en: 'A small relative of Triceratops, with a frill but no horns.',
    },
    long: {
      sv: 'Protoceratops levde i öknar i Asien och är en av de dinosaurier man hittat flest av, från nykläckta ungar till vuxna. Den hade näbb och en benkrage men inga riktiga horn. Ett berömt fossil visar en Protoceratops och en Velociraptor som dog mitt i en strid, troligen begravda av sand.',
      en: 'Protoceratops lived in deserts in Asia and is one of the dinosaurs found in the greatest numbers, from hatchlings to adults. It had a beak and a bony frill but no real horns. One famous fossil shows a Protoceratops and a Velociraptor that died in the middle of a fight, probably buried by sand.',
    },
    facts: [
      { sv: 'Den hittades tillsammans med en Velociraptor, mitt i en strid.', en: 'One was found together with a Velociraptor, in the middle of a fight.' },
      { sv: 'Forskare har hittat ungar i alla åldrar.', en: 'Scientists have found young of every age.' },
      { sv: 'Den hade en näbb som en papegoja.', en: 'It had a beak like a parrot.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på grymtningar och bräkanden.',
      en: 'Nobody knows for sure. Scientists guess at grunts and bleats.',
    },
    starter: false,
    colour: 'relatives',
    source: NHM('protoceratops'),
  },
  {
    id: 'plateosaurus',
    name: 'Plateosaurus',
    pronounce: { sv: 'pla-te-o-SAU-rus', en: 'PLAT-ee-oh-SORE-us' },
    meaning: { sv: 'Bred ödla', en: 'Broad lizard' },
    group: 'dinosaur',
    period: 'triassic',
    fromMya: 214,
    toMya: 204,
    lengthM: 8,
    heightM: 3,
    weightKg: 2000,
    sizeLike: { sv: 'Lång som en liten lastbil', en: 'As long as a small lorry' },
    diet: 'herbivore',
    found: { sv: 'Tyskland, Schweiz och Frankrike', en: 'Germany, Switzerland and France' },
    short: {
      sv: 'En av de första stora dinosaurierna. Den levde långt före de flesta andra i kortleken.',
      en: 'One of the first big dinosaurs. It lived long before most of the others in the deck.',
    },
    long: {
      sv: 'Plateosaurus levde under trias, när dinosaurierna var nya på jorden. Den gick på två ben och hade lång hals för att nå växter högt upp. Den är en tidig släkting till jättarna som Diplodocus och Brachiosaurus. I Tyskland har man hittat så många skelett att den är en av de bäst kända dinosaurierna.',
      en: 'Plateosaurus lived in the Triassic, when dinosaurs were new on Earth. It walked on two legs and had a long neck for reaching plants high up. It is an early relative of giants like Diplodocus and Brachiosaurus. So many skeletons have been found in Germany that it is one of the best-known dinosaurs.',
    },
    facts: [
      { sv: 'Den levde nästan 150 miljoner år före Tyrannosaurus rex.', en: 'It lived almost 150 million years before Tyrannosaurus rex.' },
      { sv: 'Den gick på två ben, inte fyra.', en: 'It walked on two legs, not four.' },
      { sv: 'Över hundra skelett har hittats.', en: 'Over a hundred skeletons have been found.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Forskare gissar på låga, dova ljud.',
      en: 'Nobody knows for sure. Scientists guess at low, muffled sounds.',
    },
    starter: false,
    colour: 'guess',
    source: NHM('plateosaurus'),
  },
  {
    id: 'mosasaurus',
    name: 'Mosasaurus',
    pronounce: { sv: 'mo-sa-SAU-rus', en: 'MOZE-ah-SORE-us' },
    meaning: { sv: 'Ödlan från floden Maas', en: 'Lizard of the river Meuse' },
    group: 'marine',
    period: 'cretaceous',
    fromMya: 82,
    toMya: 66,
    lengthM: 13,
    heightM: 3,
    weightKg: 10000,
    sizeLike: { sv: 'Längre än en buss', en: 'Longer than a bus' },
    diet: 'carnivore',
    found: { sv: 'Nederländerna och USA', en: 'The Netherlands and USA' },
    short: {
      sv: 'Ett jättelikt rovdjur i havet. Den var ingen dinosaurie, utan släkt med ödlor och ormar.',
      en: 'A giant hunter of the sea. It was not a dinosaur, but a relative of lizards and snakes.',
    },
    long: {
      sv: 'Mosasaurus levde i haven i slutet av kritaperioden. Den simmade med en kraftig svans med fena, ungefär som en haj, och styrde med fyra paddlar. Den åt fisk, sköldpaddor och andra havsdjur. Den andades luft och måste upp till ytan, precis som valar gör i dag.',
      en: 'Mosasaurus lived in the seas at the end of the Cretaceous. It swam with a powerful finned tail, a bit like a shark, and steered with four paddles. It ate fish, turtles and other sea animals. It breathed air and had to come up to the surface, just as whales do today.',
    },
    facts: [
      { sv: 'Den är närmare släkt med ormar än med dinosaurier.', en: 'It is more closely related to snakes than to dinosaurs.' },
      { sv: 'Den hade en extra rad tänder i gommen.', en: 'It had an extra row of teeth in the roof of its mouth.' },
      { sv: 'Det första fossilet hittades i en gruva för över 250 år sedan.', en: 'The first fossil was found in a mine over 250 years ago.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Under vatten gjorde den kanske inga ljud alls.',
      en: 'Nobody knows for sure. Under water it may have made no sounds at all.',
    },
    starter: false,
    colour: 'relatives',
    source: WIKI('Mosasaurus'),
  },
  {
    id: 'plesiosaurus',
    name: 'Plesiosaurus',
    pronounce: { sv: 'ple-si-o-SAU-rus', en: 'PLEE-see-oh-SORE-us' },
    meaning: { sv: 'Nästan en ödla', en: 'Near to lizard' },
    group: 'marine',
    period: 'jurassic',
    fromMya: 199,
    toMya: 190,
    lengthM: 3.5,
    heightM: 1.5,
    weightKg: 450,
    sizeLike: { sv: 'Lång som en bil', en: 'As long as a car' },
    diet: 'piscivore',
    found: { sv: 'England', en: 'England' },
    short: {
      sv: 'En havsreptil med lång hals och fyra simfenor. Den var ingen dinosaurie.',
      en: 'A sea reptile with a long neck and four flippers. It was not a dinosaur.',
    },
    long: {
      sv: 'Plesiosaurus simmade genom att "flyga" under vattnet med sina fyra fenor, ungefär som en havssköldpadda. Med den långa halsen och de vassa tänderna fångade den fisk och bläckfisk. Det första hela skelettet hittades 1823 av Mary Anning, en av de första stora fossiljägarna.',
      en: 'Plesiosaurus swam by "flying" under water with its four flippers, a bit like a sea turtle. With its long neck and sharp teeth it caught fish and squid. The first complete skeleton was found in 1823 by Mary Anning, one of the first great fossil hunters.',
    },
    facts: [
      { sv: 'Den hittades av Mary Anning år 1823.', en: 'It was found by Mary Anning in 1823.' },
      { sv: 'Den simmade med fyra fenor.', en: 'It swam with four flippers.' },
      { sv: 'Den födde levande ungar i havet.', en: 'It gave birth to live young in the sea.' },
    ],
    sound: {
      sv: 'Ingen vet säkert. Under vatten gjorde den kanske inga ljud alls.',
      en: 'Nobody knows for sure. Under water it may have made no sounds at all.',
    },
    starter: false,
    colour: 'relatives',
    source: WIKI('Plesiosaurus'),
  },
];
